### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by JacobDYG** [Plymouth-University-BSc-Computing/soft165-practicals-Cutwell#3]
There are three standout issues currently:
- There is no alternative text for the photo
- There is no feature to resize text
- It is unclear that content will change when hovered over, such as the photo and the word 'Everest'; Unexpected flashing can be a problem for people will epilepsy. 

The good:
- High contrast fonts used
- Clear, relevant headings placed directly by the relevant content
- The page is titled

**Comment by Cutwell** [comment]
Cheers for the feedback!
Resolved in PR #5
